version: "3.7"

services:
  mongo: # base de données mongodb
    image: mongo
    container_name: exemple-bdd-mongo
    ports:
      - 27017:27017
    volumes: 
      - ./mongo/data:/data/db

  redis:
    container_name: exemple-bdd-redis
    image: redis
    ports:
      - 6379:6379

  redis-ui:
    image: rediscommander/redis-commander:latest
    container_name: exemple-bdd-redisui
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=redis
      - PORT=8082
    ports:
      - 4001:8082
